Repository 42Blank/ft_transcendence, pull requests merged in 2023-02, with the labels that each got.

#14 Fix/cookie option
  .github/workflows/ci.yml
  backend/src/api/auth/service/login.service.ts
Labels: bug

#12 Feat: 로그인 로직 WIP
  .gitignore
  frontend/.eslintrc.js
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/assets/index.ts
  frontend/src/common/LoginLayout/index.tsx
  frontend/src/common/MainLayout/NavBar.tsx
  frontend/src/common/MainLayout/index.tsx
  frontend/src/common/constants.ts
  frontend/src/common/index.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/useCheckLogin.ts
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/logo.svg
  frontend/src/pages/LoginCallbackPage/index.tsx
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/index.ts
  frontend/src/services/getCurrentUserInfo.ts
  frontend/src/services/getFtCallbackCode.ts
  frontend/src/services/index.ts
  frontend/src/setupTests.ts
  frontend/src/store/index.ts
  frontend/src/store/userState.ts
  frontend/src/style/index.ts
  frontend/src/styles/index.ts
  frontend/src/styles/reset.css
  frontend/src/type/type.d.ts
  frontend/src/types/auth.d.ts
  frontend/src/types/type.d.ts
  frontend/src/util/index.ts
  frontend/src/utils/index.ts
Labels: enhancement

#26 Feat: 메인 페이지 (채팅목록 페이지), 게임목록 페이지, 채팅 상세 페이지, 소켓 기본적인 설정
  frontend/.eslintrc.js
  frontend/.prettierrc.js
  frontend/.prettierrc.json
  frontend/package.json
  frontend/public/icon.png
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/src/App.tsx
  frontend/src/common/MainLayout/FriendsList.styles.ts
  frontend/src/common/MainLayout/FriendsList.tsx
  frontend/src/common/MainLayout/FriendsListElement.styles.ts
  frontend/src/common/MainLayout/FriendsListElement.tsx
  frontend/src/common/MainLayout/MainLayout.styles.ts
  frontend/src/common/MainLayout/NavBar.styles.ts
  frontend/src/common/MainLayout/NavBar.tsx
  frontend/src/common/MainLayout/UserMenu.styles.ts
  frontend/src/common/MainLayout/UserMenu.tsx
  frontend/src/common/MainLayout/index.tsx
  frontend/src/common/RoomElement/RoomElement.styles.ts
  frontend/src/common/RoomElement/index.tsx
  frontend/src/common/index.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/useCheckLogin.ts
  frontend/src/hooks/useHandleSocket.ts
  frontend/src/hooks/useSetSocketHandler.ts
  frontend/src/pages/ChatPage/ChatElement.styles.ts
  frontend/src/pages/ChatPage/ChatElement.tsx
  frontend/src/pages/ChatPage/ChatInput.styles.ts
  frontend/src/pages/ChatPage/ChatInput.tsx
  frontend/src/pages/ChatPage/ChatPage.styles.ts
  frontend/src/pages/ChatPage/index.tsx
  frontend/src/pages/GameListPage/GameListPage.styles.ts
  frontend/src/pages/GameListPage/index.tsx
  frontend/src/pages/MainPage/MainPage.styles.ts
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/index.ts
  frontend/src/services/deleteAuthSignout.ts
  frontend/src/services/getCurrentUserInfo.ts
  frontend/src/services/index.ts
  frontend/src/store/currentChatDataState.ts
  frontend/src/store/index.ts
  frontend/src/store/newMessageState.ts
  frontend/src/store/userState.ts
  frontend/src/styles/reset.css
  frontend/src/types/chat.d.ts
  frontend/src/types/user.d.ts
  frontend/yarn.lock
Labels: enhancement

#39 Feat: 유저 로그인 / 로그아웃 useQuery로 수정, 채팅방 정보 모달 추가, 모달 훅 및 템플릿 추가
  frontend/.eslintrc.js
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/assets/arrowDownIcon.svg
  frontend/src/assets/editIcon.svg
  frontend/src/assets/hamburgerIcon.svg
  frontend/src/assets/index.ts
  frontend/src/common/Dropdown/Dropdown.styles.ts
  frontend/src/common/Dropdown/index.tsx
  frontend/src/common/MainLayout/FriendsListElement.styles.ts
  frontend/src/common/MainLayout/FriendsListElement.tsx
  frontend/src/common/MainLayout/UserMenu.tsx
  frontend/src/common/Modal/Modal.styles.ts
  frontend/src/common/Modal/index.tsx
  frontend/src/common/index.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/useCheckLogin.ts
  frontend/src/hooks/useGetCurrentUser.ts
  frontend/src/hooks/useHandleSocket.ts
  frontend/src/hooks/useLogout.ts
  frontend/src/index.tsx
  frontend/src/pages/ChatPage/ChatElement.styles.ts
  frontend/src/pages/ChatPage/ChatElement.tsx
  frontend/src/pages/ChatPage/ChatInfoModalHeader.styles.ts
  frontend/src/pages/ChatPage/ChatInfoModalHeader.tsx
  frontend/src/pages/ChatPage/ChatPage.styles.ts
  frontend/src/pages/ChatPage/index.tsx
  frontend/src/services/deleteAuthSignout.ts
  frontend/src/store/index.ts
  frontend/src/store/userState.ts
  frontend/src/types/chat.d.ts
  frontend/src/utils/checkIsUserOperator.ts
  frontend/src/utils/index.ts
Labels: bug, enhancement

#52 Style: 채팅 목록 순서 역순으로 변경, 숫자 줄옮김 안되는 이슈 해결
  frontend/src/hooks/useSetSocketHandler.ts
  frontend/src/pages/ChatPage/ChatElement.styles.ts
  frontend/src/pages/ChatPage/ChatElement.tsx
  frontend/src/pages/ChatPage/ChatPage.styles.ts
Labels: bug

#54 Style: Pong 에셋 추가
  frontend/public/ball.png
  frontend/public/paddle.png
  frontend/src/pages/GamePage/MainScene.tsx
Labels: enhancement

#64 Feat: 채팅방 비밀번호 입력 칸 추가, 비공개 채팅방 자물쇠 아이콘 출력, 채팅방 정보 수정 이벤트 추가
  frontend/src/assets/index.ts
  frontend/src/assets/lockIcon.svg
  frontend/src/hooks/useHandleSocket.ts
  frontend/src/pages/ChatListPage/ChatRoomElement.styles.ts
  frontend/src/pages/ChatListPage/ChatRoomElement.tsx
  frontend/src/pages/ChatListPage/NewChatModalBody.tsx
  frontend/src/pages/ChatPage/ChatElement.styles.ts
  frontend/src/pages/ChatPage/ChatModal/ChatInfoModalHeader.tsx
  frontend/src/pages/ChatPage/ChatPage.styles.ts
  frontend/src/pages/ChatPage/index.tsx
  frontend/src/store/index.ts
  frontend/src/store/updateChatRoomState.ts
  frontend/src/types/chat.d.ts
Labels: bug, enhancement

#70 Feat: 사이드바 여닫기 기능 추가, 에러 바운더리 추가, Chat 예외처리 위임 등등
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/index.ts
  frontend/src/assets/warningIcon.svg
  frontend/src/common/ErrorComponent/ErrorComponent.styles.ts
  frontend/src/common/ErrorComponent/index.tsx
  frontend/src/common/MainLayout/FriendsList.styles.ts
  frontend/src/common/MainLayout/FriendsList.tsx
  frontend/src/common/MainLayout/NavBar.styles.ts
  frontend/src/common/MainLayout/NavBar.tsx
  frontend/src/common/MainLayout/index.tsx
  frontend/src/common/RootComponent.tsx
  frontend/src/common/index.ts
  frontend/src/hooks/useGetCurrentChatRoom.ts
  frontend/src/pages/ChatListPage/ChatListPage.styles.ts
  frontend/src/pages/ChatPage/ChatModal/ChatUserListElement.styles.ts
  frontend/src/pages/ChatPage/ChatModal/ChatUserListElement.tsx
  frontend/src/pages/GameListPage/GameListPage.styles.ts
  frontend/yarn.lock
Labels: bug, enhancement

#127 Feat/profile manage buttons
  frontend/src/hooks/useGetUserList.ts
  frontend/src/pages/ProfilePage/ManageFriends.tsx
  frontend/src/pages/ProfilePage/index.tsx
  frontend/src/services/deleteFriend.ts
  frontend/src/services/postFriendOrBlock.ts
Labels: enhancement

#106 Refactor: 로그인 부분 리팩토링
  frontend/src/App.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/useGetUser.ts
  frontend/src/hooks/useGetUserList.ts
  frontend/src/hooks/useLogin.ts
  frontend/src/index.tsx
  frontend/src/pages/LoginCallbackPage/index.tsx
  frontend/src/pages/RegisterPage/RegisterPage.styles.ts
  frontend/src/pages/RegisterPage/index.tsx
  frontend/src/pages/index.ts
  frontend/src/services/axiosWrapper.ts
  frontend/src/services/deleteAuthSignout.ts
  frontend/src/services/deleteFriend.ts
  frontend/src/services/getBlockList.ts
  frontend/src/services/getFriendList.ts
  frontend/src/services/getFtCallbackCode.ts
  frontend/src/services/getLogin.ts
  frontend/src/services/getUserInfo.ts
  frontend/src/services/index.ts
  frontend/src/services/postFriendOrBlock.ts
  frontend/src/services/postRegister.ts
  frontend/src/services/putUserProfile.ts
  frontend/src/types/user.d.ts
  frontend/src/utils/delayPromise.ts
  frontend/src/utils/error/index.ts
  frontend/src/utils/error/isApiError.ts
  frontend/src/utils/index.ts
Labels: bug, enhancement

#141 !HOTFIX: delete 401 에러 수정
  frontend/src/services/axiosWrapper.ts
Labels: bug

#136 Feat/profile achievement: 업적 표시 구현
  frontend/.eslintrc.js
  frontend/src/common/Tooltip/index.tsx
  frontend/src/common/constants.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/useGetBlockList.ts
  frontend/src/hooks/useGetFriendList.ts
  frontend/src/hooks/useGetUserList.ts
  frontend/src/pages/ProfilePage/Achievement.tsx
  frontend/src/pages/ProfilePage/AchievementList.tsx
  frontend/src/pages/ProfilePage/AchievementTooltip.tsx
  frontend/src/pages/ProfilePage/ManageFriends.tsx
  frontend/src/pages/ProfilePage/ProfileCard.tsx
  frontend/src/pages/ProfilePage/index.tsx
  frontend/src/pages/ProfilePage/tmpAchievement.style.ts
  frontend/src/pages/ProfilePage/tmpAchievementTooltip.style.ts
  frontend/src/services/getBlockList.ts
  frontend/src/types/achievement.d.ts
Labels: enhancement

#144 Fix: UI 요소 이슈 해결, 권한 부여 소켓 추가 (될수도있고 안될수도있음)
  frontend/src/common/MainLayout/FriendsList.styles.ts
  frontend/src/common/MainLayout/FriendsList.tsx
  frontend/src/common/MainLayout/FriendsListElement.styles.ts
  frontend/src/common/MainLayout/FriendsListElement.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/useGetAllUserList.ts
  frontend/src/hooks/useHandleSocket.ts
  frontend/src/hooks/useSetSocketHandler.ts
  frontend/src/pages/ChatListPage/ChatListPage.styles.ts
  frontend/src/pages/ChatPage/ChatModal/ChatInfoModalBody.tsx
  frontend/src/pages/ChatPage/ChatModal/ChatInfoModalHeader.tsx
  frontend/src/pages/ChatPage/ChatModal/ChatUserListElement.tsx
  frontend/src/pages/ChatPage/index.tsx
  frontend/src/pages/GameListPage/GameListPage.styles.ts
  frontend/src/services/getAllUserList.ts
  frontend/src/services/index.ts
  frontend/src/store/giveOperatorState.ts
  frontend/src/store/index.ts
  frontend/src/store/onlineUserListState.ts
  frontend/src/store/takeOperatorState.ts
  frontend/src/types/chat.d.ts
  frontend/src/types/user.d.ts
  frontend/src/utils/checkIsUserOperator.ts
  frontend/src/utils/checkUserRole.ts
  frontend/src/utils/index.ts
Labels: bug

#145 Feat/profile match history
  frontend/src/pages/ProfilePage/Achievement.tsx
  frontend/src/pages/ProfilePage/AchievementList.tsx
  frontend/src/pages/ProfilePage/AchievementTooltip.tsx
  frontend/src/pages/ProfilePage/MatchHistory.tsx
  frontend/src/pages/ProfilePage/MatchHistoryList.tsx
  frontend/src/pages/ProfilePage/index.tsx
  frontend/src/pages/ProfilePage/tmpMatchHistory.style.ts
  frontend/src/types/achievement.d.ts
  frontend/src/types/profile.d.ts
Labels: enhancement

#146 Feat: 유저 권한 수정 및 밴, 언밴, 킥, 뮤트, 언뮤트
  backend/src/socket/chat/dto/outcoming/chat-room.dto.ts
  backend/src/socket/chat/model/chat-room.ts
  backend/src/socket/chat/repository/chat-room.repository.ts
  backend/src/socket/chat/service/chat-room.service.ts
  backend/src/socket/chat/service/chat-user-operate.service.ts
  backend/src/socket/chat/service/chat-user.service.ts
  frontend/src/assets/index.ts
  frontend/src/assets/kickIcon.svg
  frontend/src/assets/unbanIcon.svg
  frontend/src/hooks/useHandleSocket.ts
  frontend/src/pages/ChatListPage/ChatRoomElement.tsx
  frontend/src/pages/ChatPage/ChatModal/BannedUserListElement.tsx
  frontend/src/pages/ChatPage/ChatModal/ChatInfoModalBody.styles.ts
  frontend/src/pages/ChatPage/ChatModal/ChatInfoModalBody.tsx
  frontend/src/pages/ChatPage/ChatModal/ChatInfoModalHeader.tsx
  frontend/src/pages/ChatPage/ChatModal/ChatUserListElement.styles.ts
  frontend/src/pages/ChatPage/ChatModal/ChatUserListElement.tsx
  frontend/src/pages/ChatPage/index.tsx
  frontend/src/store/giveOperatorState.ts
  frontend/src/store/index.ts
  frontend/src/store/takeOperatorState.ts
  frontend/src/store/userOperationState.ts
  frontend/src/types/chat.d.ts
  frontend/src/utils/checkUserRole.ts
Labels: bug, enhancement

#151 Pong: 결과 모달 작성
  frontend/src/pages/GamePage/GameResultModalBody.styles.ts
  frontend/src/pages/GamePage/GameResultModalBody.tsx
  frontend/src/pages/GamePage/MainScene.tsx
  frontend/src/pages/GamePage/game.tsx
  frontend/src/pages/GamePage/index.tsx
Labels: Pong

#149 Refactor/profile dirs/hook calls
  frontend/src/pages/ProfilePage/Achievement/Achievement.tsx
  frontend/src/pages/ProfilePage/Achievement/AchievementList.tsx
  frontend/src/pages/ProfilePage/Achievement/AchievementTooltip.tsx
  frontend/src/pages/ProfilePage/Achievement/index.ts
  frontend/src/pages/ProfilePage/Achievement/tmpAchievement.style.ts
  frontend/src/pages/ProfilePage/Achievement/tmpAchievementTooltip.style.ts
  frontend/src/pages/ProfilePage/EditProfile.tsx
  frontend/src/pages/ProfilePage/EditProfileModal.tsx
  frontend/src/pages/ProfilePage/MatchHistory/MatchHistory.tsx
  frontend/src/pages/ProfilePage/MatchHistory/MatchHistoryList.tsx
  frontend/src/pages/ProfilePage/MatchHistory/index.ts
  frontend/src/pages/ProfilePage/MatchHistory/tmpMatchHistory.style.ts
  frontend/src/pages/ProfilePage/ProfileCard.tsx
  frontend/src/pages/ProfilePage/TwoFactorAuth.tsx
  frontend/src/pages/ProfilePage/index.tsx
  frontend/src/pages/ProfilePage/tmp.css
Labels: refactor

#156 Style/profile 프로필 페이지 기본적인 레이아웃 추가 !
  frontend/src/pages/ProfilePage/Achievement/AchievementList.tsx
  frontend/src/pages/ProfilePage/EditProfile.tsx
  frontend/src/pages/ProfilePage/MatchHistory/MatchHistory.style.ts
  frontend/src/pages/ProfilePage/MatchHistory/MatchHistory.tsx
  frontend/src/pages/ProfilePage/MatchHistory/MatchHistoryList.tsx
  frontend/src/pages/ProfilePage/MatchHistory/tmpMatchHistory.style.ts
  frontend/src/pages/ProfilePage/Profile.style.ts
  frontend/src/pages/ProfilePage/ProfileCard.style.ts
  frontend/src/pages/ProfilePage/ProfileCard.tsx
  frontend/src/pages/ProfilePage/TwoFactorAuth.tsx
  frontend/src/pages/ProfilePage/index.tsx
Labels: style

#157 Feat/profile match api
  frontend/src/common/constants.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/useGetMatchHistory.ts
  frontend/src/pages/ProfilePage/MatchHistory/MatchHistory.tsx
  frontend/src/pages/ProfilePage/MatchHistory/MatchHistoryBox.tsx
  frontend/src/pages/ProfilePage/MatchHistory/MatchHistoryList.tsx
  frontend/src/pages/ProfilePage/index.tsx
  frontend/src/services/getMatchHistory.ts
  frontend/src/services/index.ts
Labels: enhancement

#169 Feat/profile 2FA 2차인증 모달, 버튼 구현
  frontend/src/pages/ProfilePage/TwoFactorAuth.tsx
  frontend/src/pages/ProfilePage/TwoFactorAuth/Cancle2FA.tsx
  frontend/src/pages/ProfilePage/TwoFactorAuth/Enable2FA.tsx
  frontend/src/pages/ProfilePage/TwoFactorAuth/TwoFactorAuth.style.ts
  frontend/src/pages/ProfilePage/TwoFactorAuth/TwoFactorAuth.tsx
  frontend/src/pages/ProfilePage/TwoFactorAuth/index.ts
  frontend/src/store/dummy2FA.ts
  frontend/src/types/profile.d.ts
Labels: enhancement

#203 Pong: 게임방 대기기능 구현
  frontend/src/pages/GamePage/index.tsx
Labels: Pong

#201 Feat/profile 닉네임 중복체크 & 파일로 업로드
  frontend/package.json
  frontend/public/aki_sample.jpg
  frontend/public/denji_sample.png
  frontend/public/kobeni_sample.jpg
  frontend/public/makima_sample.jpg
  frontend/public/power_sample.jpg
  frontend/src/pages/ProfilePage/EditProfileModal.tsx
  frontend/src/services/putUserProfile.ts
  frontend/yarn.lock
Labels: enhancement

#225 Feat/game match making
  backend/src/common/database/repository/game-match-queue.repository.ts
  backend/src/common/database/repository/index.ts
  backend/src/common/database/repository/socket-repository.module.ts
  backend/src/socket/game/game.gateway.ts
  backend/src/socket/game/game.module.ts
  backend/src/socket/game/service/game-match-queue.service.ts
  frontend/src/pages/GamePage/GamePong.tsx
Labels: enhancement

#228 fix: 비밀번호 compare 로직 수정
  backend/src/socket/chat/service/chat-user.service.ts
Labels: bug, Urgent
